name: PR Verify

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

permissions: {}

jobs:
  bicep-lint:
    permissions:
      contents: read
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Azure CLI - Install Bicep
        run: az bicep install
      
      - name: Bicep Lint
        run: |
          az bicep build --file bicep/main.bicep
